# Generated by Django 3.2.3 on 2021-05-21 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transporter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='transporter.bus'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reach', to='transporter.bus'),
        ),
        migrations.AlterField(
            model_name='routes',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begin', to='transporter.bus'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='field_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='transporter.bus'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path', to='transporter.bus'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='passengerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengersno', to='transporter.passengers'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='schedulesid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='transporter.passengers'),
        ),
    ]
